version: 16
jobs:
- name: push to gh
  steps:
  - !PushRepository
    name: push to github
    remoteUrl: https://github.com/davidedpg10/lightDiary
    passwordSecret: GithubToken
    withLfs: false
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
