version: "3.8"
services:
  diaryweb:
    env_file:
      - .env
    build:
      context: .
      dockerfile: live_reload.Dockerfile
    container_name: diary_api
    ports:
      - ${APP_PORT}:8080
    depends_on:
      - postgresql
    volumes:
      - ../app:/app
      - ./tmp:/app/tmp
  postgresql:
    env_file:
      - .env
    image: postgres:9.6.24-alpine
    container_name: diary_postgresql
    volumes:
      - ../app/db/schema/:/docker-entrypoint-initdb.d/